---
title: "Syllabus"
author: "Slava Nikitin"
date: "2017-01-22"
weight: 10
widget: "custom"
draft: false
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Prerequisite**
Statistics I (MATH 1240) 

## **Schedule (subject to change)**

+---------------+---------------+---------------------------------------------+------------------------------+
| Module        |      Dates    |         Topics                              |  Assignments                 |
+===============+===============+=============================================+==============================+
| Explore       | - 01/09       | - Setup, Visualization                      | - Read 2 - 4                 |
|               | - 01/23       | - Data Transformation, EDA                  | - Read 5 - 8,   Assignment 1 |
+---------------+---------------+---------------------------------------------+------------------------------+
| Wrangle I     | - 01/30       | - EDA, Assignment 1                         | - Read 2 - 8                 |
|               | - 02/06       | - Import, Tibbles, Tidy                     | - Read 9 - 12                |
+---------------+---------------+---------------------------------------------+------------------------------+
| Wrangle II    | - 02/13       | - Tidy and Relational Data                  | - Read 12 - 13               |
|               | - 02/20       | - Strings, Factors, Dates, Times            | - Read 14 - 16, Assignment 2 |
+---------------+---------------+---------------------------------------------+------------------------------+
| Program       | - 03/06       | - Assignment 2, Pipes, Functions            | - Read 17 - 19               |
|               | - 03/13       | - Vectors, Iteration                        | - Read 20 - 21               |
+---------------+---------------+---------------------------------------------+------------------------------+
| Program       | - 03/20       | - Vectors, Iteration, Assignment 3          | - Read 20 - 21               |
|               | - 03/27       | - Assignment 3, Modeling basics             | - Read 22 - 23               |
+---------------+---------------+---------------------------------------------+------------------------------+
| Model         | - 04/03       | - Modeling basics                           | - Read 22 - 23               |
| Produce       | - 04/10       | - Student's choice                          | - Project work               |
+---------------+---------------+---------------------------------------------+------------------------------+
| Produce       | - 04/17       | - Student's choice                          | - Project work               |
| Share         | - 04/24       | - Student's choice                          | - Presentations              |
+---------------+---------------+---------------------------------------------+------------------------------+

## **Assignment**
- Exploratory Data Analysis
- Data Organization
- Basic Programming Concepts

## **Project**
- R package of functions useful for your work
- R markdown report of deep analysis

## **Assessment**
- 3 Assignments - 30%
- Project - 60%
- Participation - 10%

