---
title: "Syllabus"
author: "Slava Nikitin"
date: "2017-01-22"
weight: 10
widget: "custom"
draft: false
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Prerequisite**
Statistics I (MATH 1240)

## **Textbook and Equipment**
- All assignments are delivered through DataCamp and access is provided as part of the course
- A laptop is required. The classroom has a limited number of computers.

## **Schedule (subject to change)**

+---------------+---------------+---------------------------------------------+------------------------------+
| Module        |      Dates    |         Topics                              |  Assignments                 |
+===============+===============+=============================================+==============================+
| Program       | - 01/08       | - RStudio, Data Structures                  | - Rstudio, Intro to R        |
|               | - 01/22       | - Conditionals, Loops, Utilities            | - Intermediate R & Practice  |
|               | - 01/29       | - Functions                                 | - Writing Functions in R     |
+---------------+---------------+---------------------------------------------+------------------------------+
| Import        | - 01/29       | - CSV, XLS, Databases, Web, Stats Packages  | - Importing Data 1 & 2       |
+---------------+---------------+---------------------------------------------+------------------------------+
| Tidy          | - 02/05       | - Tidy Data, Types, Missingness, Outliers   | - Cleaning & Practice        |
+---------------+---------------+---------------------------------------------+------------------------------+
| Transform     | - 02/12       | - Tabular Manipulations, Relational Data    | - Data Manipulation & Joining|
|               | - 02/19       | - Strings, Dates, Times                     | - Working Strings, Date, Time|
+---------------+---------------+---------------------------------------------+------------------------------+
| Visualize     | - 03/05       | - Grammar of Graphics, Visualization        | - GGplot 1, GGplot 2         |
|               | - 03/12       | - Grammar of Graphics, Visualization, EDA   | - GGplot 2 & EDA Practice    |
+---------------+---------------+---------------------------------------------+------------------------------+
| Model         | - 03/19       | - Machine Learning: Supervised              | - Classification, Regression |
|               | - 03/26       | - Machine Learning: Unsupervised, Framework | - Clustering, caret          |
|               | - 04/02       | - Machine Learning: Text analysis           | - Bag of Words, Sentiment    |
+---------------+---------------+---------------------------------------------+------------------------------+
| Communicate   | - 04/09       | - Custom visuals, Reports, Web Apps         | - GGplot, Rmarkdown, Shiny   |
+---------------+---------------+---------------------------------------------+------------------------------+
| Produce       | - 04/16       | - Student's Choice                          | - Project work               |
+---------------+---------------+---------------------------------------------+------------------------------+
| Share         | - 04/23       | - Student's Choice                          | - Presentations              |
+---------------+---------------+---------------------------------------------+------------------------------+

## **Assignments**
Modules covering the data science production cycle: import, tidy, transform, visualize, model, communicate, program.

- [DataCamp](https://www.datacamp.com/home) provides the premium content covering relevant R packages and practice exercises
- Deadlines are meant to maintain a pace, but are not enforced. However, all assignments must be finished by the end of the semester.
- You have to work on assignments individually; there is sufficient guidance in the videos to help you move through them, as material was designed for self-study. We will also have a Q-A session in class. In general, programming and data science can only be internalized by thinking and working through the
problems yourself.

## **Project**
An interesting or work-related idea developed, documented and executed from scratch

- Collection of functions useful for your work
- Automation script
- R markdown report of deep, exploratory analysis
- Interactive web application
- Repeatable R markdown report

## **Participation**
- Class attendance is mandatory, unless there is a legitimate reason to skip, which you should communicate
- Participation in the discussion is highly encouraged

## **Assessment**
- Assignments - 45%
- Project - 45%
- Participation - 10%

## **Office Hours**
By appointment
