---
title: "Case Study 2"
summary: "Conference Proceedings Analysis"
author: "Slava Nikitin"
date: "2018-01-22"
draft: false
tags: ["lecture"]
output: 
  html_document:
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Conference Proceedings Analysis

### Project

- **Background**  
  A retail company XYZ LLC prides itself on excellent customer service. One way to deliver excellence is by listening to customer complaints about their products and services collected through various channels like email or phone. Upon receiving a complaint, it is supposed to go through a classification process assigning it a product, sub-product and progressively detailed reasons for the complaint. The purpose of the classes is to organize complaints, and enable calculation of descriptive statistics and trending to get a better insight into what needs to be adjusted and how to prioritize work. However, being a large company with many and multifaceted products, the classification tree is deep and broad. During each complaint classification cycle, a complaint can pass through subtrees with options in the dozens which is a heavy cognitive load on the customer associate. The heavy load translates into slow downs, avoidance of work, missing data, poor data quality, a need for a quality assurance process, job dissatisfaction and increased turnover. All these negative side-effects undermine delivery of excellent customer service and impose extra costs. 
- **Objectives**  
  The central task is to make the classification process much easier to reduce or eliminate its negative side-effects. Provide a wrapper around the code such that it can integrate into the existing user interface and improve the current classification process.
- **Benefits**  
  Making the classification process substantially easier will lead to 
- **Data Specification**  
  Few years of complaints data in .csv will be provided to support the work.
- **Solution**  
  Use the data generated by the complaint classification process to develop a predictive model that can take complaint text and predict class probabilities. Computed class probabilities can be used to sort the classes and only show the most likely batch. This will produce a dynamic classification process that will be sensitive to the information in the complaint and guide the customer associate towards the most fitting classes without completely removing them out of the process.

### People
- A project manager, a data scientist and a developer from Awesome Analytics.
- An expert on the complaint data and the user interface, a customer associate, developers responsible for the user interface from XYZ.   

### Process
- **Phases**  
  Emphasize, Define, Ideate, Prototype, Test, Implement
- **Communication**  
  Weekly meetings will take place to collect feedback.
- **Security Classification**  
  Data is private.
  
### Issues, Ideas and Principles
- **Purpose**  
  A predictive model integrated into an interactive user interface rather than understanding or automated actions.
- **Confidentiality**  
  Complaint data has personally identifying as well as business sensitive information.
- **Data Transfer**  
  Private data requires a more serious consideration of data transfer. For example, working on site or placing a machine in client's environment or establishing direct, encrypted transfer.
- **Data Management**  
  With confidential data you have to worry about access, provinence, and potentially destruction. A good access principle to follow is limitting access project materials only to those actually working the projects. Provinence involves recording the trail of the data as it moves around and is modified. Finally, data destruction upon project completion is a good, risk-averse practice.
- **Data Formats**  
  A .csv format is really typical, but can be generated in various ways as there is no commonly agreed upon specification. Commas and new line characters and double quotes can appear in text fields, and without properly quoting them, the separation of cells or lines can get lost.
- **Complex Transformations**  
   How to transform a piece of text into a class, especially when text is highly variable and there are hundreds of classes? No intuitive answer comes - the problem is complex, and manually constructed rules will do poorly and take enourmous time to develop. Data, however, contains many examples of what class was assigned to a piece of text. Statistical models can be used to represent a large number of possible relationship between text and class, and then data be used to find the relationship most consistent with data.
- **Assessment of Predictive Models**  
  We can split the data into two, one part for learning a relationship of text and class consistent with data, another for testing its accuracy. We could calculate overall accuracy as well as class specific accuracies.
- **Interpretability of Predictive Models**  
  Complex non-linear mathematical functions are learned to represent the relationship of text and class. What if someone wanted to know what pieces of information in the complaint contributed to it being classified in some way? Interpretability is an important aspect of understanding the learned model and providing reasons for the automated predictions.
- **Conditions of Application**  
  In this case, applying the predictive model to the whole classification tree is unnecessary and not possible from the beginning. In this project, the most impact can be achieved by considering subtrees that have more than 5 options, have sufficient data and can be handled accurately by the model.
- **Kinds and Gradations of Automation**  
  This is an example of outsourcing some mental work to a machine. If a task is repeatable and can be broken down into steps, then we can think of sharing those steps between a human and a machine, with the balance roughly giving you the amount of automation.
- **Improvement over Time**
  A system built on data can often improve with more data. In this case, predictive models will get more accurate, more parts of the classification tree can be reached systematically by a customer associate and generate data to build additional models. By putting some predictive models into a system sets a company on a trajectory of improvements. 
  
### Relevant R packages 
- **Import**  
  readr
- **Transform**  
  dplyr, stringr, text2vec
- **Visualize**  
  ggplot2
- **Model**  
  xgboost, lime
- **Automate**
  R packaging system
  









